apiVersion: v1
kind: Service
metadata:
  name: cnmu-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.63
  selector:
    app: cloudnativemauritius
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080
